"""empty message

Revision ID: 6b8e974fda60
Revises: 
Create Date: 2019-02-28 14:58:06.238600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b8e974fda60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email_UNIQUE', table_name='user')
    op.drop_index('username_UNIQUE', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('create_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('update_at', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username_UNIQUE', 'user', ['username'], unique=True)
    op.create_index('email_UNIQUE', 'user', ['email'], unique=True)
    # ### end Alembic commands ###
